### ISSUE TITLE
Remove scrollbar in Firefox from ScrollArea

### ISSUE THREAD

**Issue by MellKam** [radix-vue/radix-vue#317]
I have a problem with hiding the scroll bar in Firefox. Everything works correctly in other browsers.

<img src="https://github.com/radix-vue/radix-vue/assets/51422045/be70ed73-cfd2-497e-be61-3da9ff8e73f9" width="320px" />

<img src="https://github.com/radix-vue/radix-vue/assets/51422045/6d6ef7bd-5c46-4658-bd85-0bafa4c43928" width="320px" />

I have found a possible solution, and it works for me. https://stackoverflow.com/a/53787170/16523571

```css
[data-radix-scroll-area-viewport] {
   scrollbar-width: none;
}
```

**Comment by zernonia** [comment]
Hey @MellKam ! Can you check of this case happened for RadixUI? 
we have webkit-scrollbar set to display none, and it should be hidden in Firefox too.

**Comment by MellKam** [comment]
From radix-ui:

https://github.com/radix-ui/primitives/blob/ea6376900d54af536dbb7b71b4fefd6ec2ce9dc0/packages/react/scroll-area/src/ScrollArea.tsx#L152

```css
[data-radix-scroll-area-viewport]{
	scrollbar-width:none;
	-ms-overflow-style:none;
	-webkit-overflow-scrolling:touch;
}

[data-radix-scroll-area-viewport]::-webkit-scrollbar{
	display:none
}
```
