### ISSUE TITLE
[Bug]: Tooltip and vue transition are not working together

### ISSUE THREAD

**Issue by aleksey-hoffman** [radix-vue/radix-vue#712]
### Environment

```bash
Latest
```

### Link to minimal reproduction

Nan

### Steps to reproduce

Add `force-mount` to the portal and wrap the content with Vue transition that has a `transform` property

```vue
  <TooltipPortal force-mount>
    <Transition name="tooltip-bottom">
      <TooltipContent
        v-bind="{ ...forwarded, ...$attrs }"
        :class="['ui-tooltip-content', props.class]"
        :side="side"
      >
        <slot />
      </TooltipContent>
    </Transition>
  </TooltipPortal>
```

```css
.tooltip-bottom-enter-active,
.tooltip-bottom-leave-active {
  transition: all 0.3s ease;
}

.tooltip-bottom-enter-from,
.tooltip-bottom-leave-to {
  opacity: 0;
  transform: translateY(30px) scale(0.5);
}
```

### Describe the bug

On enter transition, the tooltip flies from the top of the window

https://github.com/radix-vue/radix-vue/assets/61761672/391f7187-79c7-48ed-9cb2-ee1b439aab71
